In [4]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import mglearn
from IPython.display import display
from sklearn.exceptions import ConvergenceWarning

In [3]:
# Define the headers since the data does not have any
headers = ["symboling", "normalized_losses", "make", "fuel_type", "aspiration",
           "num_doors", "body_style", "drive_wheels", "engine_location",
           "wheel_base", "length", "width", "height", "curb_weight",
           "engine_type", "num_cylinders", "engine_size", "fuel_system",
           "bore", "stroke", "compression_ratio", "horsepower", "peak_rpm",
           "city_mpg", "highway_mpg", "price"]

# Read in the CSV file and convert "?" to NaN
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data",
                  header=None, names=headers, na_values="?" )
df.head()

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0

In [5]:
df.dtypes

symboling              int64
normalized_losses    float64
make                  object
fuel_type             object
aspiration            object
num_doors             object
body_style            object
drive_wheels          object
engine_location       object
wheel_base           float64
length               float64
width                float64
height               float64
curb_weight            int64
engine_type           object
num_cylinders         object
engine_size            int64
fuel_system           object
bore                 float64
stroke               float64
compression_ratio    float64
horsepower           float64
peak_rpm             float64
city_mpg               int64
highway_mpg            int64
price                float64
dtype: object

In [12]:
# only select the categorical values from the dataset
obj_df=df.select_dtypes(include=["object"]).copy()
obj_df

,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,engine_type,num_cylinders,fuel_system
0,alfa-romero,gas,std,two,convertible,rwd,front,dohc,four,mpfi
1,alfa-romero,gas,std,two,convertible,rwd,front,dohc,four,mpfi
2,alfa-romero,gas,std,two,hatchback,rwd,front,ohcv,six,mpfi
3,audi,gas,std,four,sedan,fwd,front,ohc,four,mpfi
4,audi,gas,std,four,sedan,4wd,front,ohc,five,mpfi
...,...,...,...,...,...,...,...,...,...,...
200,volvo,gas,std,four,sedan,rwd,front,ohc,four,mpfi
201,volvo,gas,turbo,four,sedan,rwd,front,ohc,four,mpfi
202,volvo,gas,std,four,sedan,rwd,front,ohcv,six,mpfi
203,volvo,diesel,turbo,four,sedan,rwd,front,ohc,six,idi
204,volvo,gas,turbo,four,sedan,rwd,front,ohc,four,mpfi

In [19]:
obj_df[obj_df.isnull().any(axis=1)]

,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,engine_type,num_cylinders,fuel_system
27,dodge,gas,turbo,NaN,sedan,fwd,front,ohc,four,mpfi
63,mazda,diesel,std,NaN,sedan,fwd,front,ohc,four,idi

In [21]:
obj_df["num_doors"].value_counts()

four    114
two      89
Name: num_doors, dtype: int64

In [25]:
obj_df[obj_df.isnull()]

,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,engine_type,num_cylinders,fuel_system
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
obj_df=obj_df.fillna({"num_doors": "four"})
obj_df

,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,engine_type,num_cylinders,fuel_system
0,alfa-romero,gas,std,two,convertible,rwd,front,dohc,four,mpfi
1,alfa-romero,gas,std,two,convertible,rwd,front,dohc,four,mpfi
2,alfa-romero,gas,std,two,hatchback,rwd,front,ohcv,six,mpfi
3,audi,gas,std,four,sedan,fwd,front,ohc,four,mpfi
4,audi,gas,std,four,sedan,4wd,front,ohc,five,mpfi
...,...,...,...,...,...,...,...,...,...,...
200,volvo,gas,std,four,sedan,rwd,front,ohc,four,mpfi
201,volvo,gas,turbo,four,sedan,rwd,front,ohc,four,mpfi
202,volvo,gas,std,four,sedan,rwd,front,ohcv,six,mpfi
203,volvo,diesel,turbo,four,sedan,rwd,front,ohc,six,idi
204,volvo,gas,turbo,four,sedan,rwd,front,ohc,four,mpfi

In [30]:
obj_df["num_cylinders"].value_counts()

four      159
six        24
five       11
eight       5
two         4
twelve      1
three       1
Name: num_cylinders, dtype: int64

In [ ]:
# Find and Replace

In [36]:
cleanup_nums = {"num_doors":     {"four": 4, "two": 2},
                "num_cylinders": {"four": 4, "six": 6, "five": 5, "eight": 8,
                                  "two": 2, "twelve": 12, "three":3 }}
cleanup_nums

{'num_doors': {'four': 4, 'two': 2},
 'num_cylinders': {'four': 4,
  'six': 6,
  'five': 5,
  'eight': 8,
  'two': 2,
  'twelve': 12,
  'three': 3}}

In [37]:
obj_df.replace(cleanup_nums, inplace=True)
obj_df.head()

,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,engine_type,num_cylinders,fuel_system
0,alfa-romero,gas,std,2,convertible,rwd,front,dohc,4,mpfi
1,alfa-romero,gas,std,2,convertible,rwd,front,dohc,4,mpfi
2,alfa-romero,gas,std,2,hatchback,rwd,front,ohcv,6,mpfi
3,audi,gas,std,4,sedan,fwd,front,ohc,4,mpfi
4,audi,gas,std,4,sedan,4wd,front,ohc,5,mpfi

### Label Encoding

* convertible $\to$ 0
* hardtop $\to$ 1
* hatchback $\to$ 2
* sedan $\to$ 3
* wagon $\to$ 4

$\to$

In [33]:
obj_df.dtypes

make               object
fuel_type          object
aspiration         object
num_doors          object
body_style         object
drive_wheels       object
engine_location    object
engine_type        object
num_cylinders      object
fuel_system        object
dtype: object

In [34]:
obj_df["body_style"] = obj_df["body_style"].astype('category')
obj_df.dtypes

make                 object
fuel_type            object
aspiration           object
num_doors            object
body_style         category
drive_wheels         object
engine_location      object
engine_type          object
num_cylinders        object
fuel_system          object
dtype: object

In [38]:
obj_df.dtypes

make                 object
fuel_type            object
aspiration           object
num_doors             int64
body_style         category
drive_wheels         object
engine_location      object
engine_type          object
num_cylinders         int64
fuel_system          object
dtype: object

In [39]:
obj_df.dtypes

make                 object
fuel_type            object
aspiration           object
num_doors             int64
body_style         category
drive_wheels         object
engine_location      object
engine_type          object
num_cylinders         int64
fuel_system          object
dtype: object

In [40]:
obj_df["body_style_cat"] = obj_df["body_style"].cat
obj_df

,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,engine_type,num_cylinders,fuel_system,body_style_cat
0,alfa-romero,gas,std,2,convertible,rwd,front,dohc,4,mpfi,<pandas.core.arrays.categorical.CategoricalAcc...
1,alfa-romero,gas,std,2,convertible,rwd,front,dohc,4,mpfi,<pandas.core.arrays.categorical.CategoricalAcc...
2,alfa-romero,gas,std,2,hatchback,rwd,front,ohcv,6,mpfi,<pandas.core.arrays.categorical.CategoricalAcc...
3,audi,gas,std,4,sedan,fwd,front,ohc,4,mpfi,<pandas.core.arrays.categorical.CategoricalAcc...
4,audi,gas,std,4,sedan,4wd,front,ohc,5,mpfi,<pandas.core.arrays.categorical.CategoricalAcc...
...,...,...,...,...,...,...,...,...,...,...,...
200,volvo,gas,std,4,sedan,rwd,front,ohc,4,mpfi,<pandas.core.arrays.categorical.CategoricalAcc...
201,volvo,gas,turbo,4,sedan,rwd,front,ohc,4,mpfi,<pandas.core.arrays.categorical.CategoricalAcc...
202,volvo,gas,std,4,sedan,rwd,front,ohcv,6,mpfi,<pandas.core.arrays.categorical.CategoricalAcc...
203,volvo,diesel,turbo,4,sedan,rwd,front,ohc,6,idi,<pandas.core.arrays.categorical.CategoricalAcc...
204,volvo,gas,turbo,4,sedan,rwd,front,ohc,4,mpfi,<pandas.core.arrays.categorical.CategoricalAcc...

In [42]:
obj_df["body_style_cat"] = obj_df["body_style"].cat.codes
obj_df

,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,engine_type,num_cylinders,fuel_system,body_style_cat
0,alfa-romero,gas,std,2,convertible,rwd,front,dohc,4,mpfi,0
1,alfa-romero,gas,std,2,convertible,rwd,front,dohc,4,mpfi,0
2,alfa-romero,gas,std,2,hatchback,rwd,front,ohcv,6,mpfi,2
3,audi,gas,std,4,sedan,fwd,front,ohc,4,mpfi,3
4,audi,gas,std,4,sedan,4wd,front,ohc,5,mpfi,3
...,...,...,...,...,...,...,...,...,...,...,...
200,volvo,gas,std,4,sedan,rwd,front,ohc,4,mpfi,3
201,volvo,gas,turbo,4,sedan,rwd,front,ohc,4,mpfi,3
202,volvo,gas,std,4,sedan,rwd,front,ohcv,6,mpfi,3
203,volvo,diesel,turbo,4,sedan,rwd,front,ohc,6,idi,3
204,volvo,gas,turbo,4,sedan,rwd,front,ohc,4,mpfi,3

In [43]:
obj_df.dtypes

make                 object
fuel_type            object
aspiration           object
num_doors             int64
body_style         category
drive_wheels         object
engine_location      object
engine_type          object
num_cylinders         int64
fuel_system          object
body_style_cat         int8
dtype: object

## 2.3 One Hot Encoding

>Label encoding has the advantage that it is straightforward but it has the disadvantage that the numeric values can be “misinterpreted” by the algorithms. For example, the value of 0 is obviously less than the value of 4 but does that really correspond to the data set in real life? Does a wagon have “4X” more weight in our calculation than the convertible?

In [44]:
pd.get_dummies(obj_df, columns=["drive_wheels"]).head()

,make,fuel_type,aspiration,num_doors,body_style,engine_location,engine_type,num_cylinders,fuel_system,body_style_cat,drive_wheels_4wd,drive_wheels_fwd,drive_wheels_rwd
0,alfa-romero,gas,std,2,convertible,front,dohc,4,mpfi,0,0,0,1
1,alfa-romero,gas,std,2,convertible,front,dohc,4,mpfi,0,0,0,1
2,alfa-romero,gas,std,2,hatchback,front,ohcv,6,mpfi,2,0,0,1
3,audi,gas,std,4,sedan,front,ohc,4,mpfi,3,0,1,0
4,audi,gas,std,4,sedan,front,ohc,5,mpfi,3,1,0,0

>The pd.get_dummies() function is a pandas method used to perform one-hot encoding on categorical data. It converts categorical variables into a series of binary (0 or 1) columns, where each column represents a category and indicates whether or not that category is present in the original data

In [45]:
pd.get_dummies(obj_df, columns=["body_style", "drive_wheels"], prefix=["body", "drive"]).head()

,make,fuel_type,aspiration,num_doors,engine_location,engine_type,num_cylinders,fuel_system,body_style_cat,body_convertible,body_hardtop,body_hatchback,body_sedan,body_wagon,drive_4wd,drive_fwd,drive_rwd
0,alfa-romero,gas,std,2,front,dohc,4,mpfi,0,1,0,0,0,0,0,0,1
1,alfa-romero,gas,std,2,front,dohc,4,mpfi,0,1,0,0,0,0,0,0,1
2,alfa-romero,gas,std,2,front,ohcv,6,mpfi,2,0,0,1,0,0,0,0,1
3,audi,gas,std,4,front,ohc,4,mpfi,3,0,0,0,1,0,0,1,0
4,audi,gas,std,4,front,ohc,5,mpfi,3,0,0,0,1,0,1,0,0

>One hot encoding, is very useful but it can cause the number of columns to expand greatly if there are many unique values in a column. For the number of values in this example, it is not a problem. However this gets really challenging to manage when there are many more options

## 2.4 Custom Binary Encoding

>Depending on the data set, you may be able to use some combination of label encoding and one hot encoding to create a binary column that meets your needs for further analysis.

In [46]:
obj_df["engine_type"].value_counts()

ohc      148
ohcf      15
ohcv      13
l         12
dohc      12
rotor      4
dohcv      1
Name: engine_type, dtype: int64

In [48]:
obj_df["OHC_Code"] = np.where(obj_df["engine_type"].str.contains("ohc"), 1, 0)
obj_df["OHC_Code"]

0      1
1      1
2      1
3      1
4      1
      ..
200    1
201    1
202    1
203    1
204    1
Name: OHC_Code, Length: 205, dtype: int32

In [50]:
obj_df

,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,engine_type,num_cylinders,fuel_system,body_style_cat,OHC_Code
0,alfa-romero,gas,std,2,convertible,rwd,front,dohc,4,mpfi,0,1
1,alfa-romero,gas,std,2,convertible,rwd,front,dohc,4,mpfi,0,1
2,alfa-romero,gas,std,2,hatchback,rwd,front,ohcv,6,mpfi,2,1
3,audi,gas,std,4,sedan,fwd,front,ohc,4,mpfi,3,1
4,audi,gas,std,4,sedan,4wd,front,ohc,5,mpfi,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...
200,volvo,gas,std,4,sedan,rwd,front,ohc,4,mpfi,3,1
201,volvo,gas,turbo,4,sedan,rwd,front,ohc,4,mpfi,3,1
202,volvo,gas,std,4,sedan,rwd,front,ohcv,6,mpfi,3,1
203,volvo,diesel,turbo,4,sedan,rwd,front,ohc,6,idi,3,1
204,volvo,gas,turbo,4,sedan,rwd,front,ohc,4,mpfi,3,1

In [51]:
obj_df[["make", "engine_type", "OHC_Code"]].head()

          make engine_type  OHC_Code
0  alfa-romero        dohc         1
1  alfa-romero        dohc         1
2  alfa-romero        ohcv         1
3         audi         ohc         1
4         audi         ohc         1

## Scikit-learn for encoding

In [53]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
cities = ["paris", "paris", "tokyo", "amsterdam"] 

le.fit_transform(cities)

array([1, 1, 2, 0], dtype=int64)

In [58]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder

lb_make= LabelEncoder()
obj_df["make_code"] = lb_make.fit_transform(obj_df["make"])
obj_df["make_code"]

0       0
1       0
2       0
3       1
4       1
       ..
200    21
201    21
202    21
203    21
204    21
Name: make_code, Length: 205, dtype: int32

In [59]:
obj_df[["make", "make_code"]].head(11)

           make  make_code
0   alfa-romero          0
1   alfa-romero          0
2   alfa-romero          0
3          audi          1
4          audi          1
5          audi          1
6          audi          1
7          audi          1
8          audi          1
9          audi          1
10          bmw          2

In [1]:
pwd

'C:\\Users\\sajja\\Practise folder'

>>>>>>>>> ### LabelBinarizer

Binarize labels in a one-vs-all fashion. Several regression and binary classification algorithms are available in scikit-learn. A simple way to extend these algorithms to the multi-class classification case is to use the so-called one-vs-all scheme.

In [65]:
obj_df["body_style"]

0      convertible
1      convertible
2        hatchback
3            sedan
4            sedan
          ...
200          sedan
201          sedan
202          sedan
203          sedan
204          sedan
Name: body_style, Length: 205, dtype: category
Categories (5, object): ['convertible', 'hardtop', 'hatchback', 'sedan', 'wagon']

In [60]:
from sklearn.preprocessing import LabelBinarizer

lb_style = LabelBinarizer()
lb_results = lb_style.fit_transform(obj_df["body_style"])
lb_results

array([[1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       ...,
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0]])

In [67]:
pd.DataFrame(lb_results, columns=lb_style.classes_)

     convertible  hardtop  hatchback  sedan  wagon
0              1        0          0      0      0
1              1        0          0      0      0
2              0        0          1      0      0
3              0        0          0      1      0
4              0        0          0      1      0
..           ...      ...        ...    ...    ...
200            0        0          0      1      0
201            0        0          0      1      0
202            0        0          0      1      0
203            0        0          0      1      0
204            0        0          0      1      0

[205 rows x 5 columns]

In [80]:
! pip install --upgrade category_encoders
! pip install --upgrade numpy
! pip install category_encoders==1.23.1

Requirement already up-to-date: category_encoders in c:\users\sajja\anaconda3\lib\site-packages (2.6.3)
Requirement already satisfied, skipping upgrade: pandas>=1.0.5 in c:\users\sajja\anaconda3\lib\site-packages (from category_encoders) (1.1.3)
Requirement already satisfied, skipping upgrade: importlib-resources; python_version < "3.9" in c:\users\sajja\anaconda3\lib\site-packages (from category_encoders) (6.0.1)
Requirement already satisfied, skipping upgrade: numpy>=1.14.0 in c:\users\sajja\anaconda3\lib\site-packages (from category_encoders) (1.24.4)
Requirement already satisfied, skipping upgrade: statsmodels>=0.9.0 in c:\users\sajja\anaconda3\lib\site-packages (from category_encoders) (0.12.0)
Requirement already satisfied, skipping upgrade: scipy>=1.0.0 in c:\users\sajja\anaconda3\lib\site-packages (from category_encoders) (1.5.2)
Requirement already satisfied, skipping upgrade: scikit-learn>=0.20.0 in c:\users\sajja\anaconda3\lib\site-packages (from category_encoders) (1.3.2)
Requirement already satisfied, skipping upgrade: patsy>=0.5.1 in c:\users\sajja\anaconda3\lib\site-packages (from category_encoders) (0.5.1)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.7.3 in c:\users\sajja\anaconda3\lib\site-packages (from pandas>=1.0.5->category_encoders) (2.8.1)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in c:\users\sajja\anaconda3\lib\site-packages (from pandas>=1.0.5->category_encoders) (2020.1)
Requirement already satisfied, skipping upgrade: zipp>=3.1.0; python_version < "3.10" in c:\users\sajja\anaconda3\lib\site-packages (from importlib-resources; python_version < "3.9"->category_encoders) (3.4.0)
Requirement already satisfied, skipping upgrade: threadpoolctl>=2.0.0 in c:\users\sajja\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (2.1.0)
Requirement already satisfied, skipping upgrade: joblib>=1.1.1 in c:\users\sajja\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (1.3.2)
Requirement already satisfied, skipping upgrade: six in c:\users\sajja\anaconda3\lib\site-packages (from patsy>=0.5.1->category_encoders) (1.15.0)
Requirement already up-to-date: numpy in c:\users\sajja\anaconda3\lib\site-packages (1.24.4)

ERROR: Could not find a version that satisfies the requirement category_encoders==1.23.1 (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.8, 1.3.0, 2.0.0, 2.1.0, 2.2.2, 2.3.0, 2.4.0, 2.4.1, 2.5.0, 2.5.1, 2.5.1.post0, 2.6.0, 2.6.1, 2.6.2, 2.6.3)
ERROR: No matching distribution found for category_encoders==1.23.1

NameError: name 'ce' is not defined

In [84]:
import category_encoders as ce


# Get a new clean dataframe
obj_df2 = df.select_dtypes(include=['object']).copy()

# Specify the columns to encode then fit and transform
encoder = ce.backward_difference.BackwardDifferenceEncoder(cols=["engine_type"])
encoder.fit(obj_df2, verbose=1)

# Only display the first 8 columns for brevity
encoder.transform(obj_df2).head()#iloc[:,6:10].head()

AttributeError: module 'numpy' has no attribute 'MachAr'

In [85]:
import numpy as np

def machine_epsilon():
  """Returns the machine epsilon."""
  return np.finfo(np.float64).eps

# Calculate the machine epsilon
machine_epsilon = machine_epsilon()

# Use the machine epsilon to calculate the backward difference encoding
encoder = ce.backward_difference.BackwardDifferenceEncoder(cols=["engine_type"])
encoder.fit(obj_df2, machine_epsilon=machine_epsilon)
encoded_df = encoder.transform(obj_df2)

NameError: name 'ce' is not defined

In [86]:
encoder = ce.polynomial.PolynomialEncoder(cols=["engine_type"])
encoder.fit(obj_df2, verbose=1)
encoder.transform(obj_df2).iloc[:,6:15].head()

NameError: name 'ce' is not defined

In [1]:
pwd

'C:\\Users\\sajja\\Practise folder'

In [1]:
import sklearn
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
encoded_text = vectorizer.fit_transform(["This is the first document.", "This is the second document."])

In [2]:
encoded_text

<2x6 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [5]:
import numpy as np
import pandas as pd
from sklearn.datasets import fetch_20newsgroups
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import TfidfVectorizer
from sklearn.cluster import KMeans

# Load the 20 newsgroups training dataset
newsgroups_train = fetch_20newsgroups(subset='train', remove=('headers', 'footers', 'quotes'))

# Create a Pandas DataFrame from the training dataset
df_train = pd.DataFrame([newsgroups_train.data, newsgroups_train.target.tolist()]).T
df_train.columns = ['text', 'target']

# Create a TfidfVectorizer object
vectorizer = TfidfVectorizer()

# Encode the text data
encoded_text = vectorizer.fit_transform(df_train['text'])

# Convert the sparse matrix to a dense matrix
dense_encoded_text = encoded_text.toarray()

# Split the dense matrix
split_encoded_text = dense_encoded_text.split()

# Create a KMeans clustering model with 20 clusters
kmeans = KMeans(n_clusters=20)

# Fit the KMeans model to the encoded data
kmeans.fit(encoded_text)

ImportError: cannot import name 'TfidfVectorizer' from 'sklearn.preprocessing' (C:\Users\sajja\anaconda3\lib\site-packages\sklearn\preprocessing\__init__.py)

In [17]:
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

# Load the dummy dataset
X_dummy = np.random.rand(100, 60)
# Load the best model
best_model = LogisticRegression(C=10, penalty='l2')
# Fit the model to the training data
best_model.fit(X_dummy, y_dummy)

NameError: name 'y_dummy' is not defined

In [25]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# Load the dummy dataset
X_dummy = np.random.rand(100, 60)
y_dummy = np.random.randint(0, 2, 100)

# Split the dataset into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_dummy, y_dummy, test_size=0.25, random_state=42)

# Create a logistic regression model
model = LogisticRegression()

# Fit the model to the training data
model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model.predict_proba(X_test)[:, 1]

# Evaluate the model's performance
accuracy = np.mean(y_pred > 0.5 == y_test)
print("Accuracy:", accuracy)

# Identify the customers with the highest probability of churning
customers_at_risk_of_churn = X_test[y_pred > 0.5]

# Print the customers at risk of churning
print(customers_at_risk_of_churn)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()